# Generated by Django 4.1.2 on 2022-12-17 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categorieId', models.AutoField(primary_key=True, serialize=False)),
                ('nomCategorie', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('experienceId', models.AutoField(primary_key=True, serialize=False)),
                ('nomExperience', models.CharField(max_length=255)),
                ('dateExperience', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fermes',
            fields=[
                ('fermeId', models.AutoField(primary_key=True, serialize=False)),
                ('nomFerme', models.CharField(max_length=255)),
                ('addresseFerme', models.CharField(max_length=255)),
                ('villeFerme', models.CharField(max_length=255)),
                ('provinceFerme', models.CharField(max_length=255, null=True)),
                ('deleted', models.BooleanField(null=True)),
                ('deletedDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NiveauAcces',
            fields=[
                ('accesId', models.AutoField(primary_key=True, serialize=False)),
                ('access', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usagers',
            fields=[
                ('usagerId', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=255, unique=True)),
                ('prenomUsager', models.CharField(max_length=255)),
                ('nomUsager', models.CharField(max_length=255)),
                ('motPasse', models.CharField(max_length=50)),
                ('accesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsagerApp.niveauacces')),
            ],
        ),
        migrations.CreateModel(
            name='Vaches',
            fields=[
                ('vacheId', models.AutoField(primary_key=True, serialize=False)),
                ('nomVache', models.CharField(max_length=255)),
                ('fermeId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UsagerApp.fermes')),
            ],
        ),
        migrations.CreateModel(
            name='UsagersFermes',
            fields=[
                ('usagersFermesId', models.AutoField(primary_key=True, serialize=False)),
                ('fermeId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UsagerApp.fermes')),
                ('usagerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsagerApp.usagers')),
            ],
        ),
        migrations.CreateModel(
            name='SousCategories',
            fields=[
                ('sousCategorieId', models.AutoField(primary_key=True, serialize=False)),
                ('nomSousCategorie', models.CharField(max_length=255)),
                ('categorieId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UsagerApp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('noteId', models.AutoField(primary_key=True, serialize=False)),
                ('dateNote', models.DateField()),
                ('note', models.CharField(max_length=255)),
                ('experienceId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UsagerApp.experiences')),
            ],
        ),
        migrations.CreateModel(
            name='Medias',
            fields=[
                ('mediaId', models.AutoField(primary_key=True, serialize=False)),
                ('media', models.BinaryField()),
                ('noteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UsagerApp.notes')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fermes',
            constraint=models.UniqueConstraint(fields=('nomFerme', 'addresseFerme', 'villeFerme'), name='uniqueFerme'),
        ),
        migrations.AddField(
            model_name='experiences',
            name='categorieId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UsagerApp.categories'),
        ),
        migrations.AddField(
            model_name='experiences',
            name='sousCategorieId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UsagerApp.souscategories'),
        ),
        migrations.AddField(
            model_name='experiences',
            name='vacheId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UsagerApp.vaches'),
        ),
        migrations.AddConstraint(
            model_name='vaches',
            constraint=models.UniqueConstraint(fields=('nomVache', 'fermeId'), name='uniqueVacheFerme'),
        ),
        migrations.AddConstraint(
            model_name='usagersfermes',
            constraint=models.UniqueConstraint(fields=('usagerId', 'fermeId'), name='uniqueUsagerFerme'),
        ),
        migrations.AddConstraint(
            model_name='souscategories',
            constraint=models.UniqueConstraint(fields=('nomSousCategorie', 'categorieId'), name='uniqueCatSouscat'),
        ),
    ]
