# Generated by Django 4.1.2 on 2022-10-22 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fermes',
            fields=[
                ('fermeId', models.AutoField(primary_key=True, serialize=False)),
                ('nomFerme', models.CharField(max_length=255)),
                ('addresseFerme', models.CharField(max_length=255)),
                ('villeFerme', models.CharField(max_length=255)),
                ('provinceFerme', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NiveauAcces',
            fields=[
                ('accesId', models.AutoField(primary_key=True, serialize=False)),
                ('access', models.CharField(max_length=355)),
            ],
        ),
        migrations.CreateModel(
            name='Usagers',
            fields=[
                ('usagerId', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('prenomUsager', models.CharField(max_length=255)),
                ('nomUsager', models.CharField(max_length=255)),
                ('motPasse', models.TextField()),
                ('accesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsagerApp.niveauacces')),
            ],
        ),
        migrations.CreateModel(
            name='UsagersFermes',
            fields=[
                ('usagersFermesId', models.AutoField(primary_key=True, serialize=False)),
                ('fermeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsagerApp.fermes')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsagerApp.usagers')),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('experienceId', models.AutoField(primary_key=True, serialize=False)),
                ('dateExperience', models.DateField(auto_now_add=True)),
                ('nomCategorie', models.CharField(max_length=255)),
                ('nomSousCategorie', models.CharField(max_length=255)),
                ('fermeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsagerApp.fermes')),
            ],
        ),
    ]
