# Generated by Django 4.1.2 on 2022-12-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='nomCategorie',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='niveauacces',
            name='access',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usagers',
            name='login',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='fermes',
            constraint=models.UniqueConstraint(fields=('nomFerme', 'addresseFerme', 'villeFerme'), name='uniqueFerme'),
        ),
        migrations.AddConstraint(
            model_name='souscategories',
            constraint=models.UniqueConstraint(fields=('nomSousCategorie', 'categorieId'), name='uniqueCatSouscat'),
        ),
        migrations.AddConstraint(
            model_name='usagersfermes',
            constraint=models.UniqueConstraint(fields=('usagerId', 'fermeId'), name='uniqueUsagerFerme'),
        ),
        migrations.AddConstraint(
            model_name='vaches',
            constraint=models.UniqueConstraint(fields=('nomVache', 'fermeId'), name='uniqueVacheFerme'),
        ),
    ]
