# Generated by Django 4.1.2 on 2022-12-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0002_alter_categories_nomcategorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usagers',
            old_name='accesId',
            new_name='NiveauAcces',
        ),
    ]
