# Generated by Django 4.1.2 on 2022-12-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0003_rename_accesid_usagers_niveauacces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='souscategories',
            old_name='categorieId',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='usagers',
            old_name='NiveauAcces',
            new_name='accesId',
        ),
    ]
