# Generated by Django 4.1.2 on 2022-12-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0004_rename_categorieid_souscategories_categories_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='souscategories',
            name='uniqueCatSouscat',
        ),
    ]
