# Generated by Django 4.1.2 on 2022-12-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0005_remove_souscategories_uniquecatsouscat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='souscategories',
            old_name='Categories',
            new_name='categories',
        ),
    ]
