# Generated by Django 4.1.2 on 2022-12-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0006_rename_categories_souscategories_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='souscategories',
            old_name='categories',
            new_name='categorieId',
        ),
        migrations.AddConstraint(
            model_name='souscategories',
            constraint=models.UniqueConstraint(fields=('nomSousCategorie', 'categorieId'), name='uniqueCatSouscat'),
        ),
    ]
