# Generated by Django 4.1.2 on 2022-12-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0007_rename_categories_souscategories_categorieid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='souscategories',
            name='uniqueCatSouscat',
        ),
        migrations.RenameField(
            model_name='souscategories',
            old_name='categorieId',
            new_name='categorie',
        ),
    ]
