# Generated by Django 4.1.2 on 2022-12-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0008_remove_souscategories_uniquecatsouscat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='souscategories',
            old_name='categorie',
            new_name='categorieId',
        ),
        migrations.AddConstraint(
            model_name='souscategories',
            constraint=models.UniqueConstraint(fields=('nomSousCategorie', 'categorieId'), name='uniqueCatSouscat'),
        ),
    ]
