# Generated by Django 4.1.2 on 2022-12-10 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0009_rename_categorie_souscategories_categorieid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='sousCategorieId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='UsagerApp.souscategories'),
            preserve_default=False,
        ),
    ]
