# Generated by Django 4.1.2 on 2022-12-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0010_experiences_souscategorieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagers',
            name='motPasse',
            field=models.CharField(editable=False, max_length=16),
        ),
    ]
