# Generated by Django 4.1.2 on 2022-12-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0011_alter_usagers_motpasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagers',
            name='motPasse',
            field=models.CharField(max_length=16),
        ),
    ]
