# Generated by Django 4.1.2 on 2022-12-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0012_alter_usagers_motpasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagers',
            name='motPasse_md5',
            field=models.CharField(default=123456, editable=False, max_length=16),
            preserve_default=False,
        ),
    ]
