# Generated by Django 4.1.2 on 2022-12-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0013_usagers_motpasse_md5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagers',
            name='motPasse_md5',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
