# Generated by Django 4.1.2 on 2022-12-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsagerApp', '0014_alter_usagers_motpasse_md5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagers',
            name='motPasse_md5',
        ),
    ]
